[phases.setup]
nixPkgs = ["python3", "pip", "chromium", "chromedriver-bin"]

[phases.install] 
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "python3 app.py"

[variables]
PYTHONUNBUFFERED = "1"
CHROME_BIN = "/nix/store/*/bin/chromium"